import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateSchema1761727037649 implements MigrationInterface {
    name = 'UpdateSchema1761727037649'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`room_types\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`room_types\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`room_types\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`room_types\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP FOREIGN KEY \`FK_8a380bdc519b8701daf0ec62da0\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP FOREIGN KEY \`FK_7a61484af364d0d804b21b25c7f\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`room_amenities\` \`room_amenities\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`room_type_id\` \`room_type_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`hotel_id\` \`hotel_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`hotels\` DROP FOREIGN KEY \`FK_656dce2a8012700e598a45cfd3f\``);
        await queryRunner.query(`ALTER TABLE \`hotels\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`hotels\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`hotels\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`hotels\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`hotels\` CHANGE \`logo\` \`logo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`hotels\` CHANGE \`email_hotel\` \`email_hotel\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`hotels\` CHANGE \`location\` \`location\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`hotels\` CHANGE \`zone_id\` \`zone_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`zones\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`zones\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zones\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`zones\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` DROP FOREIGN KEY \`FK_be5cd3c6d04d0ce156fcadd7e72\``);
        await queryRunner.query(`ALTER TABLE \`booking_details\` DROP FOREIGN KEY \`FK_57f3269d238d3af5420e6e4fe89\``);
        await queryRunner.query(`ALTER TABLE \`booking_details\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`booking_details\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`booking_details\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` CHANGE \`checkin_date\` \`checkin_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` CHANGE \`checkout_date\` \`checkout_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` CHANGE \`booking_id\` \`booking_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` CHANGE \`room_id\` \`room_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_44342bfa812465df91df3d9a152\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_cbd0eedd8fe9da9bc391902e70a\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`bookings\` CHANGE \`customer_name\` \`customer_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`bookings\` CHANGE \`customer_tel\` \`customer_tel\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`bookings\` CHANGE \`created_by\` \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bookings\` CHANGE \`updated_by\` \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD CONSTRAINT \`FK_8a380bdc519b8701daf0ec62da0\` FOREIGN KEY (\`room_type_id\`) REFERENCES \`room_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD CONSTRAINT \`FK_7a61484af364d0d804b21b25c7f\` FOREIGN KEY (\`hotel_id\`) REFERENCES \`hotels\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`hotels\` ADD CONSTRAINT \`FK_656dce2a8012700e598a45cfd3f\` FOREIGN KEY (\`zone_id\`) REFERENCES \`zones\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` ADD CONSTRAINT \`FK_be5cd3c6d04d0ce156fcadd7e72\` FOREIGN KEY (\`booking_id\`) REFERENCES \`bookings\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` ADD CONSTRAINT \`FK_57f3269d238d3af5420e6e4fe89\` FOREIGN KEY (\`room_id\`) REFERENCES \`rooms\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_44342bfa812465df91df3d9a152\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_cbd0eedd8fe9da9bc391902e70a\` FOREIGN KEY (\`updated_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_cbd0eedd8fe9da9bc391902e70a\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_44342bfa812465df91df3d9a152\``);
        await queryRunner.query(`ALTER TABLE \`booking_details\` DROP FOREIGN KEY \`FK_57f3269d238d3af5420e6e4fe89\``);
        await queryRunner.query(`ALTER TABLE \`booking_details\` DROP FOREIGN KEY \`FK_be5cd3c6d04d0ce156fcadd7e72\``);
        await queryRunner.query(`ALTER TABLE \`hotels\` DROP FOREIGN KEY \`FK_656dce2a8012700e598a45cfd3f\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP FOREIGN KEY \`FK_7a61484af364d0d804b21b25c7f\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP FOREIGN KEY \`FK_8a380bdc519b8701daf0ec62da0\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` CHANGE \`updated_by\` \`updated_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bookings\` CHANGE \`created_by\` \`created_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bookings\` CHANGE \`customer_tel\` \`customer_tel\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bookings\` CHANGE \`customer_name\` \`customer_name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_cbd0eedd8fe9da9bc391902e70a\` FOREIGN KEY (\`updated_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_44342bfa812465df91df3d9a152\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` CHANGE \`room_id\` \`room_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` CHANGE \`booking_id\` \`booking_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` CHANGE \`checkout_date\` \`checkout_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` CHANGE \`checkin_date\` \`checkin_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`booking_details\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`booking_details\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` ADD CONSTRAINT \`FK_57f3269d238d3af5420e6e4fe89\` FOREIGN KEY (\`room_id\`) REFERENCES \`rooms\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking_details\` ADD CONSTRAINT \`FK_be5cd3c6d04d0ce156fcadd7e72\` FOREIGN KEY (\`booking_id\`) REFERENCES \`bookings\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`zones\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`zones\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zones\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`zones\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`hotels\` CHANGE \`zone_id\` \`zone_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`hotels\` CHANGE \`location\` \`location\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`hotels\` CHANGE \`email_hotel\` \`email_hotel\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`hotels\` CHANGE \`logo\` \`logo\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`hotels\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`hotels\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`hotels\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`hotels\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`hotels\` ADD CONSTRAINT \`FK_656dce2a8012700e598a45cfd3f\` FOREIGN KEY (\`zone_id\`) REFERENCES \`zones\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`hotel_id\` \`hotel_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`room_type_id\` \`room_type_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`room_amenities\` \`room_amenities\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD CONSTRAINT \`FK_7a61484af364d0d804b21b25c7f\` FOREIGN KEY (\`hotel_id\`) REFERENCES \`hotels\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD CONSTRAINT \`FK_8a380bdc519b8701daf0ec62da0\` FOREIGN KEY (\`room_type_id\`) REFERENCES \`room_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`room_types\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`room_types\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`room_types\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`room_types\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
    }

}
